version: "3.9"

services:
  nest:
    container_name: nest
    build:
      context: ./ticket-nest
      target: development
    volumes:
      - ./ticket-nest:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
